spring:
  config:
    import: optional:file:./.env[.properties]

  application:
    name: media-service

  web:
    resources:
      add-mappings: false
  kafka:
    bootstrap-servers: localhost:9092, localhost:9093
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: media-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


  data:
    mongodb:
#        database: ${DB_NAME}
#        username: ${DB_USER}
#        password: ${DB_PASSWORD}
#        port: ${DB_PORT}
#        host: ${DB_HOST}
#        auto-index-creation: true
#        authentication-database: ${DB_AUTH_DB}
      uri: mongodb+srv://${DB_USER}:${DB_PASSWORD}@buy0x.mqr2hhc.mongodb.net/?retryWrites=true&w=majority&appName=buy0x
      database: ${DB_NAME}
      auto-index-creation: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:${EUREKA_SERVER_PORT}/eureka/


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

server:
  port: 8083

aws:
  s3:
    bucket: hackaton-groupe10
  region: eu-north-1
  credentials:
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}

logging:
  level:
    org.apache.kafka: ERROR
    kafka: ERROR

