spring:
  config:
    import: optional:file:./.env.dev[.properties]

  application:
    name: user-service

  web:
    resources:
      add-mappings: false

  data:
    mongodb:
      uri: mongodb+srv://${DB_USER}:${DB_PASSWORD}@buy0x.mqr2hhc.mongodb.net/?retryWrites=true&w=majority&appName=buy0x
      database: ${DB_NAME}
      auto-index-creation: true
  kafka:
    bootstrap-servers: localhost:9092, localhost:9093
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: user-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:${EUREKA_SERVER_PORT}/eureka/

application:
  security:
    jwt:
      secret: ${JWT_SECRET}
      expiration-ms: 600000
      refresh-expiration: 3600000

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

server:
  port: 8081