spring:
    data:
        mongodb:
            uri: mongodb+srv://${DB_USER:user}:${DB_PASSWORD:password}@buy0x.mqr2hhc.mongodb.net/?retryWrites=true&w=majority&appName=buy0x
            database: ${DB_NAME:testdb}
            auto-index-creation: true

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:${EUREKA_SERVER_PORT:8761}/eureka/
